<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        Product::insert([
            [
                'name' => 'Cashmere Ribbed Cardigan',
                'category' => 'Cardigan',
                'material' => 'Cashmere',
                'price' => 1500000,
                'img' => 'https://i.pinimg.com/1200x/8d/08/28/8d0828d51cfc26c57e0cb10974ebb04c.jpg',
                'is_flash_sale' => true,
                'discount_percent' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coach Ribbon Shoulder Bag',
                'category' => 'Bags',
                'material' => 'Leather',
                'price' => 51200000,
                'img' => 'https://i.pinimg.com/736x/76/a0/ff/76a0ffa9055eff73cafdec1f87478b40.jpg',
                'is_flash_sale' => true,
                'discount_percent' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Milan Leather Jordan Shoes',
                'category' => 'Shoes',
                'material' => 'Leather',
                'price' => 53900000,
                'img' => 'https://i.pinimg.com/736x/9c/b9/10/9cb910dc405be286b9b09f1de23056e4.jpg',
                'is_flash_sale' => true,
                'discount_percent' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Denim Long Trousers',
                'category' => 'Pants',
                'material' => 'Denim',
                'price' => 950000,
                'img' => 'https://images.unsplash.com/photo-1718252540511-e958742e4165?w=500&auto=format&fit=crop&q=60',
                'is_flash_sale' => true,
                'discount_percent' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Leather Backpack',
                'category' => 'Bags',
                'material' => 'Leather',
                'price' => 22000000,
                'img' => 'https://i.pinimg.com/736x/52/f2/b0/52f2b090b2b3245e201b84bae187d2a6.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chelsea Ankle Boots',
                'category' => 'Shoes',
                'material' => 'Leather',
                'price' => 22800000,
                'img' => 'https://i.pinimg.com/736x/a3/8f/b5/a38fb5b1fe8ec8432fc978e7dfedb150.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chelsea Shirt Denim',
                'category' => 'Shirt',
                'material' => 'Denim',
                'price' => 2800000,
                'img' => 'https://i.pinimg.com/1200x/2d/ee/9d/2dee9d8c644da4093caa117e97cbf150.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Brown Louis Vuitton',
                'category' => 'Bags',
                'material' => 'Leather',
                'price' => 35000000,
                'img' => 'https://i.pinimg.com/1200x/34/b7/c0/34b7c03d20fbdd628e141c6834bacd6a.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Flower Applique Cap Sleeve',
                'category' => 'Shirt',
                'material' => 'Cotton',
                'price' => 2500000,
                'img' => 'https://i.pinimg.com/1200x/2d/b6/2a/2db62aa07bb2e682d07f95b53c0aa6b8.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dior Diorissimo Vintage Flower',
                'category' => 'Bags',
                'material' => 'Canvas',
                'price' => 42000000,
                'img' => 'https://i.pinimg.com/1200x/75/95/9a/75959a02a721662ec269f6b4df46892a.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tank Top Polkadot',
                'category' => 'Shirt',
                'material' => 'Cotton',
                'price' => 580000,
                'img' => 'https://i.pinimg.com/736x/6b/19/dd/6b19dd66a91b9091ecac651262f62a81.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Black Short Pants',
                'category' => 'Pants',
                'material' => 'Cotton',
                'price' => 195000,
                'img' => 'https://i.pinimg.com/736x/ff/0c/50/ff0c502438dd06c2bae7c12439395178.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dark Brown Short-sleeved Shirt',
                'category' => 'Shirt',
                'material' => 'Cotton',
                'price' => 420000,
                'img' => 'https://i.pinimg.com/1200x/14/50/c4/1450c4370485587662dbd32dd5997173.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Star Print Parachute Pants',
                'category' => 'Pants',
                'material' => 'Parachute',
                'price' => 380000,
                'img' => 'https://i.pinimg.com/736x/02/c4/7d/02c47d09612bcd4814a4ab178edad7a1.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classic Trench Coat',
                'category' => 'Cardigan',
                'material' => 'Leather',
                'price' => 18500000,
                'img' => 'https://i.pinimg.com/1200x/81/b9/58/81b9585d45134a38934277e4cca77496.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minimalist Tote Bag',
                'category' => 'Bags',
                'material' => 'Leather',
                'price' => 21200000,
                'img' => 'https://i.pinimg.com/1200x/75/7c/a7/757ca7b73b9e3e8bafe7c813a098441c.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Flatshoes Ribbon',
                'category' => 'Shoes',
                'material' => 'Leather',
                'price' => 4500000,
                'img' => 'https://i.pinimg.com/736x/29/26/aa/2926aaa8c9acfbf2703176239e99f87c.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Linen Wide Leg Pants',
                'category' => 'Pants',
                'material' => 'Linen',
                'price' => 3200000,
                'img' => 'https://i.pinimg.com/1200x/83/f6/ad/83f6ada86ceabaeedfff2cacb6034e81.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oversized Knit Sweater',
                'category' => 'Cardigan',
                'material' => 'Cardigan',
                'price' => 4100000,
                'img' => 'https://i.pinimg.com/inimg/cd/bc/9f/cdbc9f6bfeb97e3e665c3981e6ae728f.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Knit Top Brown',
                'category' => 'Shirt',
                'material' => 'Cotton',
                'price' => 1800000,
                'img' => 'https://i.pinimg.com/1200x/8f/45/04/8f45047b552790bbe2316ae0040e30d5.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elegant Silk One Set',
                'category' => 'Shirt',
                'material' => 'Silk',
                'price' => 500000,
                'img' => 'https://i.pinimg.com/736x/5d/ef/9c/5def9c4cee1d9edbc4d75251d77aad48.jpg',
                'is_flash_sale' => false,
                'discount_percent' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
